### ISSUE TITLE
Data: NYT

### ISSUE THREAD

**Issue by houtanb** [forecastingresearch/forecastbench#2]
Source|Task
-- | --
NYT | news topics

**Comment by pythoryn** [comment]
Pros: Variety of topics. Less noise than GDELT.
Cons: Less data rich than GDELT. Same issue as with GDELT: forecasting mentions of something it's not a very specific forecasting question. Also limits with their general terms usage of API: "Prohibit caching or archiving content and providing archived datasets to others without permission" so we would need to ask for permission and that might incur a delay.
