### ISSUE TITLE
Data: DBnomics

### ISSUE THREAD

**Issue by houtanb** [forecastingresearch/forecastbench#6]
Source|Task
-- | --
DBnomics | US
DBnomics | Europe
DBnomics | Asia
DBnomics | Africa

**Comment by pythoryn** [comment]
DBnomics
Pros: variety of topics, dataset source implementation already in place
Cons: very few datasets are up to date. The few that are tent to be stats agencies or central banks from just a few countries: Germany, Ireland, Italy, Australia and for most of them for a very reduced set of topics concentrated around the domain of economics. DESTATIS (Federal Statistical Office Germany) is the exception with very diverse in types of topics (births, deaths, airports passengers, electricity consumption, etc) and updated with high frequency, but it would constraint all the forecasting questions to Germany.

Eurostat 
Pros: variety of topics
Cons: irregular updating, few time series are up to date. Not anywhere as good as FRED in terms of updating frequency. Only a few time series update monthly, most related to economics/finance

OECD
Pros: great diversity of topics
Cons: Most time series are not outdated monthly.
